version: "3.7"
services:
  web:
    image: node:12-alpine
    working_dir: /app
    volumes:
      - ./web:/app
    command: sh -c "yarn install && yarn run build && yarn start"
    ports:
       - 3000:3000
  server:
    image: node:12-alpine
    working_dir: /app
    depends_on:
      - db
    volumes:
      - ./server:/app
    command: sh -c "yarn install && yarn run start"
    ports:
       - 3001:3001
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example