version: "3.7"
services:
  web:
    image: node:12-alpine
    working_dir: /app
    volumes:
      - ./web:/app
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_SERVER_URL=http://localhost:3001
  server:
    image: node:12-alpine
    working_dir: /app
    depends_on:
      - db
    volumes:
      - ./server:/app
    command: sh -c "yarn install && yarn run dev"
    ports:
       - 3001:3001
    environment:
      - JWT_ACCESS_KEY=safjsdjafs021#!@fweif@#d
      - JWT_REFRESH_KEY=we@!#!Efasfsafdssdf
      - DB_URL=mongodb://soso01:testtest@mongo/nest?authSource=admin 
  db:
    image: mongo
    container_name: mongo
    restart: always
    ports:
       - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: soso01
      MONGO_INITDB_ROOT_PASSWORD: testtest
      MONGO_INITDB_DATABASE: nest